name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: AI PR Review
        uses: aryannaithani/ai-review-fin@v1.3.2
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
